#!/bin/bash

file_path="data.json"
if [ ! -f "$file_path" ]; then
    echo "File $file_path does not exist."
    exit 1
fi

name=$(jq -r '.name' "$file_path")
type=$(jq -r '.types[0].type.name' "$file_path")
height=$(jq -r '.height' "$file_path")
weight=$(jq -r '.weight' "$file_path")
formatted_height=$(echo "$height" | awk '{printf "%.1f", $1 / 10}')
formatted_weight=$(echo "$weight" | awk '{printf "%.0f", $1 / 10}')

name=$(echo "$name" | sed 's/.*/\u&/')
type=$(echo "$type" | sed 's/.*/\u&/')

echo "$name is of type $type, weighs ${formatted_weight}kg, and is ${formatted_height}m tall."
